### ISSUE TITLE
Error When Creating features

### ISSUE THREAD

**Issue by hpreischel** [hsosik/ifcb-analysis#2]
I am getting the same error when trying to run features on start_fileset_tamug and with the features training code. 

> Undefined function 'statxture' for input arguments of type 'uint8'.
> 
> Error in blob_texture (line 9)
> texture = statxture(img_adjusted(find(target.blob_image)));
> 
> Error in bin_features (line 62)
>     target = blob_texture(target);
> 
> Error in batch_features (line 50)
>             bin_features(in_dir{filecount}, [char(filelist(filecount)) '.roi'], out_dir, [], in_dir_blob{filecount});
> 
> Error in start_fileset_tamug (line 27)
> batch_features( in_dir, bins, out_dir, in_dir_blob );

When I run the 'start_fileset_tamug'  script line by line I receive an empty output after running line 12: bins_temp = dir([in_dir_temp '*.adc']); 
It finds my files when I run line 11 that creates the in_dir_temp variable, but I suppose it cannot find the .adc files... 

Any idea why this may be happening?

**Comment by hsosik** [comment]
This error does not appear to have anything to do with finding adc 
files. The error lines indicate you are missing access to the function 
statxture.m. That function is part of the DIPUM toolbox, which is one of 
the requirements listed (with an access link) near the top of this wiki 
page:

https://github.com/hsosik/ifcb-analysis/wiki

On 2/19/2016 5:27 PM, hpreischel wrote:

> I am getting the same error when trying to run features on 
> start_fileset_tamug and with the features training code.
> 
> ```
> Undefined function 'statxture' for input arguments of type 'uint8'.
> 
> Error in blob_texture (line 9)
> texture = statxture(img_adjusted(find(target.blob_image)));
> 
> Error in bin_features (line 62)
> target = blob_texture(target);
> 
> Error in batch_features (line 50)
> bin_features(in_dir{filecount}, [char(filelist(filecount))
> '.roi'], out_dir, [], in_dir_blob{filecount});
> 
> Error in start_fileset_tamug (line 27)
> batch_features( in_dir, bins, out_dir, in_dir_blob );
> ```
> 
> When I run the 'start_fileset_tamug' script line by line I receive an 
> empty output after running line 12: bins_temp = dir([in_dir_temp 
> '*.adc']);
> It finds my files when I run line 11 that creates the in_dir_temp 
> variable, but I suppose it cannot find the .adc files...
> 
> Any idea why this may be happening?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/hsosik/ifcb-analysis/issues/2.

## 

Heidi M. Sosik
Biology Department, MS 32
Woods Hole Oceanographic Institution
Woods Hole, MA  02543-1049
phone: 508-289-2311  fax: 508-457-2134
hsosik@whoi.edu  http://www.whoi.edu/sites/hsosik/
