### ISSUE TITLE
Old *.config files are not compatable after pulling from repository on 10.6.16 and other new issues

### ISSUE THREAD

**Issue by eepeacock** [hsosik/ifcb-analysis#21]
After pulling from the repository today, I cannot start from any existing *.config files, and nor can I load an old *.config file after starting in 'default' config.

I tried making a new *.config, and one thing that was strange was that when a path was wrong, it just showed a blank box instead of files listed in red. 

I did save the *.config and "start manual classify", which appeared to run, but I did not try annotating anything. Then, when I chose "quit", everthing closed, even the little startMC  window! Lots of Red text in MATLAB command window.

I restarted and tried annotations. They appear to be working fine. 

This time when I quit from manual classify "startMC" stayed open. 

Tried again to load my old configuration. No luck. If I save it and open it again, there are only classes in my class list (Asterionellopsis and Ceratium)! How weird!

Okay, I know this is a string of random comments, but I just wanted to mention as much evidence as possible. Please let me know if you want more details on any aspect or when I should try again. Or if you can think of anything on my end that would have caused all of these problems!

**Comment by hsosik** [comment]
Fixed in commit 26ef63a.
