### ISSUE TITLE
-v7.3 switch

### ISSUE THREAD

**Issue by Phytoplanktonic** [hsosik/ifcb-analysis#23]
I was having difficulty with the make_TreeBaggerClassifier_user_training.m. When I would run it, the output .mat file didn’t contain the ‘b’ variable (the TreeBagger output). When I stepped through the code, MATLAB reported that it could only save ‘b’ if I used the -v7.3 switch in the call to ‘save’. Adding the switch solved this problem on my end.

**Comment by hsosik** [comment]
I cannot reproduce this problem. I am running MATLAB 2016a. Is this specific to some MATLAB version?

**Comment by hsosik** [comment]
It looks like this problem may only show up in cases with large 'b' variables. And I am not sure it happens for recent versions of MATLAB. I will need to do more tests (and/or find out what MATLAB version Phytoplanktonic is using).

**Comment by hsosik** [comment]
I updated make_TreeBaggerClassifier_user_training.m to include the '-v7.3' switch for saving classifiers. I am not 100% sure what impact this might have on compression and save/load times for the classifier, but I think this will at least avoid the crash the now occurs for cases where the classifier structure is large.
