### ISSUE TITLE
make_TreeBaggerClassifier_user_training example inputs missing an input

### ISSUE THREAD

**Issue by drkthomp** [hsosik/ifcb-analysis#30]
The example given for this function: 

> result_path = 'C:\work\IFCB\user_training_test_data\manual\summary\'; %USER location of training file and classifier output
>  train_filename = 'UserExample_Train_06Aug2015'; %USER what file contains your training features
>  nTrees = 100; %USER how many trees in your forest; choose enough to reach asymptotic error rate in "out-of-bag" classifications

You're missing the result_str. It's included in the example use of the function, and isn't hard to figure out, but you should include it in example inputs since running this function with only three inputs causes an error. 

This issue is similarly present in the wiki page for 'Make and evalute a random forest classifier' where it states: 
> The function make_TreeBaggerClassifier_user_training takes three input variables:
> 1. string specifying local directory for compiled training set (features) and classifier output,
> 2. string specifying name of file that contains your training features,
> 3. number of decision trees to include in the assemblage (forest).

**Comment by hsosik** [comment]
Comment lines in the m-file updated and committed; wiki text updated and committed.
