### ISSUE TITLE
start_blob_batch_user_training.m extra lines in script prevents it from running

### ISSUE THREAD

**Issue by kristie-r** [hsosik/ifcb-analysis#34]
There seems to be some code in the start_blob_batch_user_training.m file which hasn't been taken away or % in the daydir lines.

**Comment by hsosik** [comment]
Should be corrected now if you pull again from the repo.

**Comment by kristie-r** [comment]
Thanks for the fix ...I've got the lastest version form the repo now and i have the same issue but in the start_feature_batch_user_training. Also with the blob files should the output folders should they start with a D or does the feature function add that? When I run the start_feature_batch_user_training with the daydir lines changed I get a an error in the unzip and its not able to find the file name

**Comment by hsosik** [comment]
committed edits to start_blob_batch_user_training.m (one more line needed to be commented out) and start_feature_batch_user_training.m; I did a more complete test run with both scripts this round, so I hope the problems are now gone!
