### ISSUE TITLE
IFCB_volume_analyzed_fromADC fails if more than one adc filename is passed in (unconfirmed)

### ISSUE THREAD

**Issue by joefutrelle** [hsosik/ifcb-analysis#35]
This line of code will fail if `length(adcfilename)` > 1, since `looktime` will be the same size as `adcfilename`:

https://github.com/hsosik/ifcb-analysis/blob/84804f89e9134f8e11ba21e61bcf76a7979ef8d9/IFCB_tools/IFCB_volume_analyzed_fromADC.m#L64

I believe that code was intended to be run inside the loop, like it is here:

https://github.com/hsosik/ifcb-analysis/blob/84804f89e9134f8e11ba21e61bcf76a7979ef8d9/IFCB_tools/IFCB_volume_analyzed.m#L46

**Comment by hsosik** [comment]
Fixed in commit: [b076862](https://github.com/hsosik/ifcb-analysis/commit/b076862a4b5e152755c724718d03b991d0ae61da)
